version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    allow:
      - dependency-type: direct
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    labels:
      - "dependencies"
      - "workflows"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "main"
    allow:
      - dependency-type: direct
    schedule:
      interval: "daily"
    versioning-strategy: increase
    commit-message:
      prefix: "Composer"
      prefix-development: "Composer Dev"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
